id: A0F0D4818
title: Prayer to Jamyang Khyentse Wangpo, Jamgön Kongtrul and Jamyang Khyentse Chökyi
  Lodrö
type: translation
pechas:
- I390F9273
- IEFB5622F
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:35:39.528451
  last_modified_at: 2023-01-04 12:35:39.528456
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I390F9273/4004: B1A6
  IEFB5622F/DAB8: B1A6
